# ENVIRONMENT OPTIONS
DOCUMENT_NAME	= document
DOCUMENT_PATH	= .
BUILD_PATH		= ./build
OUTPUT_PATH		= .

# COMPILING OPTIONS
COMPILER		= pdflatex
COMPILER_FLAGS	= -halt-on-error -output-directory=$(BUILD_PATH)
BIBER			= biber
BIBER_FLAGS		= --input-directory $(BUILD_PATH) --output-directory $(BUILD_PATH)

# ALIASES
BUILD_FILES		= $(BUILD_PATH)/$(DOCUMENT_NAME).{log,aux,bcf,out,run.xml,toc}
BIB_FILES		= $(BUILD_PATH)/$(DOCUMENT_NAME).{bbl,blg}

default: help

help:
	@echo "These are all the options available:"
	@echo "build - compile the .tex files to generate the pdf"
	@echo "clean - remove all the files generated by the 'build' option."
	@echo "cleanall - remove all the files generated by the 'build' option, including the pdf file."
	@echo "help - show this message."

build: cleanall
	mkdir -p $(BUILD_PATH)
	$(COMPILER) $(COMPILER_FLAGS) $(DOCUMENT_PATH)/$(DOCUMENT_NAME).tex \
	&& mv $(BUILD_PATH)/$(DOCUMENT_NAME).pdf $(OUTPUT_PATH)

clean:
	rm -f $(BUILD_FILES)
	rm -f $(BIB_FILES)

cleanall: clean
	rm -f $(OUTPUT_PATH)/$(DOCUMENT_NAME).pdf

